algoritmo "Aula02"

var
   N1, N2, A,B,C,D: real
inicio
      Escreva("Informe um numero:")
      Leia(N1)
      Escreva("Informe outro numero:")
      Leia(N2)
      A<-N1+N2
      B<-N1-N2
      C<-N1*N2
      D<-N1/N2
      Escreval("O resultado da soma é: ",A)
      Escreval("O resultado da subtraçao é: ",B)
      Escreval("O resultado da multiplicacao é: ",C)
      Escreval("O resultado da divisao é: ",D)
fimalgoritmo
